import React from 'react'
import { render, screen, act } from '@testing-library/react'
import Activity from './Activity'
const offline={schemaVersion:1,generatedAt:null,sourceObservedAt:null,lastSuccessAt:null,health:'offline',events:[]}
const response=data=>({ok:true,headers:{get:()=>null},text:async()=>JSON.stringify(data)})
beforeEach(()=>{jest.useFakeTimers();global.fetch=jest.fn().mockResolvedValue(response(offline));Object.defineProperty(document,'hidden',{configurable:true,value:false})})
afterEach(()=>{jest.useRealTimers();delete global.fetch})
test('empty real feed is explicitly offline with no invented events',async()=>{render(<Activity/>);await act(async()=>{});expect(screen.getByText('⚪ source offline. no lore invented.')).toBeInTheDocument();expect(screen.getByText('no successful source check yet.')).toBeInTheDocument();expect(screen.getByText('no verified updates yet. peaceful scrollback, honestly.')).toBeInTheDocument();expect(fetch).toHaveBeenCalledWith('/activity/feed.json',expect.objectContaining({cache:'no-store'}));})
test('inactive tab makes no request',async()=>{render(<Activity active={false}/>);await act(async()=>{});expect(fetch).not.toHaveBeenCalled();})
test('polling pauses while hidden and refreshes on visibility return',async()=>{render(<Activity/>);await act(async()=>{});Object.defineProperty(document,'hidden',{configurable:true,value:true});await act(async()=>{jest.advanceTimersByTime(60000)});expect(fetch).toHaveBeenCalledTimes(1);Object.defineProperty(document,'hidden',{configurable:true,value:false});await act(async()=>{document.dispatchEvent(new Event('visibilitychange'))});expect(fetch).toHaveBeenCalledTimes(2);})
test('invalid input is disconnected and cannot render raw/private prose',async()=>{fetch.mockResolvedValue(response({...offline,secret:'private-prose'}));render(<Activity/>);await act(async()=>{});expect(screen.getByText('refresh didn’t land. old receipts stay old. 💤')).toBeInTheDocument();expect(screen.queryByText('private-prose')).not.toBeInTheDocument();})
test('old source checks stay stale despite successful fetch',async()=>{const old=new Date(Date.now()-20*60000).toISOString();fetch.mockResolvedValue(response({...offline,generatedAt:old,sourceObservedAt:old,lastSuccessAt:old,health:'healthy'}));render(<Activity/>);await act(async()=>{});expect(screen.getByText('🟡 last check got sleepy. these updates are old.')).toBeInTheDocument();})
test('unmount aborts and stops polling',async()=>{const {unmount}=render(<Activity/>);await act(async()=>{});const signal=fetch.mock.calls[0][1].signal;unmount();expect(signal.aborted).toBe(true);await act(async()=>{jest.advanceTimersByTime(120000)});expect(fetch).toHaveBeenCalledTimes(1);})
test('feed request is fixed GET without credentials, redirects or cross-origin reads',async()=>{render(<Activity/>);await act(async()=>{});expect(fetch).toHaveBeenCalledWith('/activity/feed.json',expect.objectContaining({method:'GET',mode:'same-origin',credentials:'omit',redirect:'error',referrerPolicy:'no-referrer'}));})
test('hostile public command/callback/html fields cannot create requests or executable DOM',async()=>{fetch.mockResolvedValue(response({...offline,url:'http://127.0.0.1:9999/execute',command:'touch /tmp/not-executed',html:'<img src=x onerror=alert(1)>',callback:'https://example.invalid/'}));const {container}=render(<Activity/>);await act(async()=>{});expect(fetch).toHaveBeenCalledTimes(1);expect(container.querySelectorAll('img,iframe,script,form,a,button')).toHaveLength(0);expect(container.textContent).not.toContain('not-executed');expect(screen.getByText('refresh didn’t land. old receipts stay old. 💤')).toBeInTheDocument();})

test('oversized streamed public payload cancels before decoding or rendering',async()=>{const cancel=jest.fn();const read=jest.fn().mockResolvedValueOnce({done:false,value:new Uint8Array(65536)}).mockResolvedValueOnce({done:false,value:new Uint8Array(65537)});fetch.mockResolvedValue({ok:true,headers:{get:()=>null},body:{getReader:()=>({read,cancel})}});render(<Activity/>);await act(async()=>{});expect(cancel).toHaveBeenCalledTimes(1);expect(read).toHaveBeenCalledTimes(2);expect(screen.getByText('refresh didn’t land. old receipts stay old. 💤')).toBeInTheDocument();});
