const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {project,digest,writeAtomic,markFailure}=require('./activity-projector.cjs');const C=require('../src/activity/contract.js');
const now=new Date();const ago=ms=>new Date(now.getTime()-ms).toISOString();
function fixture(overrides={},pinOverrides={}) {
 const receipt={schemaVersion:1,taskId:'synthetic-task',attemptId:'synthetic-attempt',revision:'a'.repeat(40),occurredAt:ago(3600000),verification:'tested',evidenceSha256:'b'.repeat(64),...overrides};
 const bytes=JSON.stringify(receipt);const pin={sourceId:'synthetic-source',receiptSha256:digest(bytes),project:'website',agent:'builder',action:'checks_passed',...pinOverrides};return observed([{sourceId:pin.sourceId,bytes}],[pin]);
}
function observed(receipts,sources) {const observation=JSON.stringify({schemaVersion:1,checkedAt:now.toISOString(),sourceSetSha256:digest(JSON.stringify([...sources].sort((a,b)=>a.sourceId.localeCompare(b.sourceId)))),evidenceSha256:'d'.repeat(64)});return {receipts,observation,policy:{schemaVersion:1,sources,observationSha256:digest(observation)}};}
function run(f=fixture()){return project(f.receipts,f.policy,f.observation,now);}
test('finite public projection omits all source IDs and private receipt fields',()=>{const f=run();assert.equal(f.events.length,1);assert.equal(f.events[0].summary,'🧪 Website · Builder passed the recorded checks.');for(const x of ['synthetic-task','synthetic-source','synthetic-attempt','evidenceSha256','revision'])assert.ok(!JSON.stringify(f).includes(x));});
test('reject free prose, URLs, private keys and sensitive categories',()=>{for(const key of ['summary','url','notes','account','host'])assert.throws(()=>run(fixture({[key]:'private'})));for(const project of ['finance','jobs','home','__proto__','constructor'])assert.throws(()=>run(fixture({}, {project})));});
test('reject missing pins, mismatch, unobserved pin and unsupported envelope',()=>{const f=fixture();assert.throws(()=>project(f.receipts,{schemaVersion:1,sources:[],observationSha256:null},null,now));f.receipts[0].bytes+=' ';assert.throws(()=>run(f));const g=fixture();assert.throws(()=>project([],g.policy,g.observation,now));g.receipts[0].extra=true;assert.throws(()=>run(g));});
test('evidence states cannot become acceptance or stronger verification',()=>{for(const verification of ['accepted','deployed','recorded'])assert.throws(()=>run(fixture({verification})));});
test('timestamps reject malformed, future and impossible dates',()=>{for(const occurredAt of ['yesterday',new Date(now.getTime()+86400000).toISOString(),'2026-02-31T00:00:00.000Z'])assert.throws(()=>run(fixture({occurredAt})));});
test('duplicate replay is idempotent; changed revision is a new event',()=>{const f=fixture();f.receipts.push(f.receipts[0]);assert.equal(run(f).events.length,1);const changed=run(fixture({revision:'c'.repeat(40)}));assert.notEqual(changed.events[0].eventId,run().events[0].eventId);});
test('30day retention removes expired receipts;100latest events retained',()=>{assert.equal(run(fixture({occurredAt:ago(31*86400000)})).events.length,0);const receipts=[],sources=[];for(let i=0;i<101;i++){const f=fixture({taskId:'synthetic-'+i},{sourceId:'source-'+i});receipts.push(f.receipts[0]);sources.push(f.policy.sources[0]);}assert.equal(run(observed(receipts,sources)).events.length,100);});
test('unconfigured source remains honest offline',()=>{const f=project([],{schemaVersion:1,sources:[],observationSha256:null},null,now);assert.equal(f.health,'offline');assert.equal(f.lastSuccessAt,null);assert.deepEqual(f.events,[]);});
test('source failure preserves successful timestamp and historical events',()=>{const f=run();const stale=markFailure(f,new Date(now.getTime()+300000));assert.equal(stale.health,'stale');assert.equal(stale.lastSuccessAt,f.lastSuccessAt);assert.deepEqual(stale.events,f.events);});
test('public input rejects unknown keys and forged summaries',()=>{const f=run();assert.throws(()=>C.validateFeed({...f,secret:'x'},now.getTime()));f.events[0].summary='<script>fake</script>';assert.throws(()=>C.validateFeed(f,now.getTime()));});
test('atomic output readback/restart and failed validation retain prior file',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'activity-'));try{const p=path.join(dir,'feed.json');const f=run();writeAtomic(p,f);assert.deepEqual(JSON.parse(fs.readFileSync(p,'utf8')),f);const before=fs.readFileSync(p,'utf8');assert.throws(()=>writeAtomic(p,{...f,secret:true}));assert.equal(fs.readFileSync(p,'utf8'),before);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('cached receipts never advance source freshness',()=>{const f=fixture(),later=new Date(new Date(now.getTime()+86400000).toISOString());const feed=project(f.receipts,f.policy,f.observation,later);assert.equal(feed.generatedAt,later.toISOString());assert.equal(feed.lastSuccessAt,now.toISOString());assert.equal(feed.sourceObservedAt,now.toISOString());assert.equal(feed.health,'stale');});
test('source observation must be independently pinned and bound to exact sources',()=>{const f=fixture();assert.throws(()=>project(f.receipts,f.policy,null,now));assert.throws(()=>project(f.receipts,f.policy,f.observation+' ',now));const o=JSON.parse(f.observation);o.sourceSetSha256='e'.repeat(64);f.observation=JSON.stringify(o);f.policy.observationSha256=digest(f.observation);assert.throws(()=>run(f));});

test('CLI accepts exact observation JSON bytes and writes validated output',()=>{const {spawnSync}=require('node:child_process');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'activity-cli-'));try {const f=fixture();for(const [name,raw] of [['receipts',JSON.stringify(f.receipts)],['policy',JSON.stringify(f.policy)],['observation',f.observation]])fs.writeFileSync(path.join(dir,name+'.json'),raw);const out=path.join(dir,'feed.json');const child=spawnSync(process.execPath,[__filename.replace('.test.cjs','.cjs'),...['receipts','policy','observation'].map(n=>path.join(dir,n+'.json')),out],{encoding:'utf8'});assert.equal(child.status,0,child.stderr);assert.equal(JSON.parse(fs.readFileSync(out,'utf8')).lastSuccessAt,now.toISOString());}finally{fs.rmSync(dir,{recursive:true,force:true});}});
